name: story_stack
description: Instagram stories like UI with rich animations and customizability. Forked from the story package.
version: 0.0.1
homepage: https://github.com/msxenon/story_stack

environment:
  sdk: '>=3.12.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
 
